spring:
  application:
    name: BotCV-Server
  config:
    import: optional:file:.env[.properties]
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?stringtype=unspecified
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USERNAME}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
          secret-key: ${JWT_SECRET}
          access-token:
            expiration: ${ACCESS_TOKEN_EXPIRATION}
          refresh-token:
            expiration: ${REFRESH_TOKEN_EXPIRATION}
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    time-zone: Asia/Ho_Chi_Minh

cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
app:
  cloudinary:
    base-url: ${CLOUDINARY_BASE_URL}
  frontend-url: ${FRONTEND_URL}
  ner-service-url: ${NER_SERVICE_URL}
  search-service-url: ${SEARCH_SERVICE_URL}
  recommendation-service-url: ${RECOMMENDATION_SERVICE_URL}
  default-avatar-public-id: ${DEFAULT_AVT_PUBLIC_ID}